PreCommit:
  TrailingWhitespace:
   enabled: true
   exclude:
     - 'target/**/*'

PrePush:
  CargoTest:
    enabled: true
    description: 'Run Cargo tests'
    required_executable: 'cargo'
    flags: ['test']
    requires_files: true
    include: "**/*.rs"
